---
- name: Install prerequisites
  apt:
    name: ["sysfsutils"]
    update_cache: yes

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: set sysctl vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    sysctl_set: yes

- name: set sysctl vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "2097152"
    state: present
    sysctl_set: yes

- name: set sysctl vm.overcommit_memory
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    sysctl_set: yes

- name: set sysctl net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    sysctl_set: yes

- name: set sysctl net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes

- name: set net.ipv6.conf.default.forwarding
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: "1"
    state: present
    sysctl_set: yes

- name: set sysctl fs.file-max
  sysctl:
    name: fs.file-max
    value: "2097152"
    state: present
    sysctl_set: yes


- name: "Set SysCtl max_user_instances to 8192"
  sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    state: present
    sysctl_set: yes

- name: "Set SysCtl max_user_watches to 524288"
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
    sysctl_set: yes



- name: set sysfs
  copy:
    dest: /etc/sysfs.conf
    content: |
      kernel/mm/transparent_hugepage/enabled = never
      kernel/mm/transparent_hugepage/defrag = never
    mode: "0644"

- name: apply sysfs transparent_hugepage/enabled
  shell: if test -f /sys/kernel/mm/transparent_hugepage/enabled; then echo never > /sys/kernel/mm/transparent_hugepage/enabled; fi
  args:
    executable: /bin/bash
  register: starthttpdout1
  changed_when: false

- name: apply sysfs transparent_hugepage/defrag
  shell: if test -f /sys/kernel/mm/transparent_hugepage/defrag; then echo never > /sys/kernel/mm/transparent_hugepage/defrag;fi
  register: starthttpdout2
  changed_when: false
  args:
    executable: /bin/bash

- name: set pam_limits configuration
  copy:
    dest: /etc/security/limits.conf
    content: |
      root            soft     nofile          65536
      root            hard     nofile          65536
      root            soft     memlock         unlimited
      root            hard     memlock         unlimited
      docker          soft     nofile          65536
      docker          hard     nofile          65536
      docker          soft     memlock         unlimited
      docker          hard     memlock         unlimited
    mode: "-rw-r--r--"

- name: enable pam_limits module
  lineinfile:
    path: /etc/pam.d/common-session
    line: session required pam_limits.so
  notify: 
    - reboot machine
